Using Statistical Functions in NumPy

We have some statistical functions (we explain the concept first and then the syntax then the interpreter) 

amin() 
to find minimum value/element from axis = 0, axis = 1 and complete array

amax() 
to find maximum value/element w respect to axis = 0, axis = 1 and complete array

average() 
to find average and weighted average from complete array & weighted average

mean() 
to find a given mean

median() 
to find a median value

var() 
to find variance for a given element

std() 
standard deviation a complete array

Minimal and Maximal Values in NumPy

In [3]:
import numpy as np

In [3]:
a=np.array([[10,20,30],[50,70,60],[1,2,3]])

In [4]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [5]:
np.amin(a)

1

In [6]:
np.amax(a)

70

In [7]:
np.amin(a,axis=0)

array([1, 2, 3])

In [8]:
np.amin(a,axis=1)

array([10, 50,  1])

In [9]:
np.amax(a,axis=0)

array([50, 70, 60])

In [10]:
np.amax(a,axis=1)

array([30, 70,  3])

Averages and Variance in NumPy

In [12]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [11]:
np.average(a)

27.333333333333332

In [13]:
w=[1,2,3]

In [14]:
np.average(a,weights=w,axis=0)

array([18.83333333, 27.66666667, 26.5       ])

In [15]:
np.average(a,weights=w,axis=1)

array([23.33333333, 61.66666667,  2.33333333])

In [16]:
np.mean(a)

27.333333333333332

In [17]:
np.mean(a,axis=0)

array([20.33333333, 30.66666667, 31.        ])

In [18]:
np.mean(a,axis=1)

array([20., 60.,  2.])

In [19]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [20]:
np.median(a) # -- 1 2 3 10 20 30 50 60 70 

20.0

In [21]:
np.median(a,axis=0)

array([10., 20., 30.])

In [22]:
np.median(a,axis=1)

array([20., 60.,  2.])

In [23]:
np.var(a)

632.2222222222223

In [24]:
np.std(a)

25.144029554194816

Statistical Order Functions in NumPy

ptp is range value from maximum to the minimum values from axis/array

In [4]:
x = np.array([[4, 9, 2, 10],[6, 9, 7, 12]])

In [5]:
print(x)

[[ 4  9  2 10]
 [ 6  9  7 12]]


In [6]:
np.ptp(x, axis=1)

array([8, 6])

In [7]:
np.ptp(x, axis=0)

array([2, 0, 5, 2])

In [8]:
np.ptp(x)

10

In [9]:
y = np.array([[1, 127],[0, 127],[-1, 127],[-2, 127]], dtype=np.int8)

In [10]:
print(y)

[[  1 127]
 [  0 127]
 [ -1 127]
 [ -2 127]]


In [11]:
np.ptp(y, axis=1)

array([ 126,  127, -128, -127], dtype=int8)

In [12]:
np.ptp(y, axis=1).view(np.uint8)

array([126, 127, 128, 129], dtype=uint8)

percentiles

In [14]:
c = np.array([[10, 7, 4], [3, 2, 1]])

In [15]:
print(c)

[[10  7  4]
 [ 3  2  1]]


In [17]:
np.percentile(c, 50)

3.5

In [19]:
np.percentile(c, 50, axis=0)

array([6.5, 4.5, 2.5])

In [20]:
np.percentile(c, 50, axis=1)

array([7., 2.])

In [21]:
np.percentile(c, 50, axis=1, keepdims=True)

array([[7.],
       [2.]])

In [22]:
m = np.percentile(c, 50, axis=0)

In [23]:
out = np.zeros_like(m)

In [24]:
np.percentile(c, 50, axis=0, out=out)

array([6.5, 4.5, 2.5])

In [25]:
print(m)

[6.5 4.5 2.5]


In [26]:
d = c.copy()

In [27]:
np.percentile(d, 50, axis=1, overwrite_input=True)

array([7., 2.])

In [28]:
assert not np.all(c == d)

Quantiles

In [29]:
c

array([[10,  7,  4],
       [ 3,  2,  1]])

In [31]:
np.quantile(c, 0.5)

3.5

In [32]:
np.quantile(c, 0.5, axis=0)

array([6.5, 4.5, 2.5])

In [34]:
np.quantile(c, 0.5, axis=1)

array([7., 2.])

In [35]:
np.quantile(c, 0.5, axis=1, keepdims=True)

array([[7.],
       [2.]])

In [36]:
n = np.quantile(c, 0.5, axis=0)

In [37]:
out = np.zeros_like(n)

In [38]:
np.quantile(c, 0.5, axis=0, out=out)

array([6.5, 4.5, 2.5])

In [39]:
n

array([6.5, 4.5, 2.5])

In [40]:
e = c.copy()

In [41]:
np.quantile(e, 0.5, axis=1, overwrite_input=True)

array([7., 2.])

In [44]:
assert not np.all(e == c)

Quantiles - other examples

In [45]:
my_list = [8,4,4,3,2,4,1,3,5,2,1,3,7] # Create example
print(my_list)                        # Print example

[8, 4, 4, 3, 2, 4, 1, 3, 5, 2, 1, 3, 7]


In [46]:
print(np.quantile(my_list, q = np.arange(0.25,1,0.25))) # 1st thing 1st - Get Quartiles of list

[2. 3. 4.]


In [47]:
print(np.quantile(my_list, q = np.arange(0.1,1,0.1))) # Get Deciles of List

[1.2 2.  2.6 3.  3.  4.  4.  4.6 6.6]


In [48]:
print(np.quantile(my_list, q = np.arange(0.01,1,0.01))) # Get Percentiles of List

[1.   1.   1.   1.   1.   1.   1.   1.   1.08 1.2  1.32 1.44 1.56 1.68
 1.8  1.92 2.   2.   2.   2.   2.   2.   2.   2.   2.   2.12 2.24 2.36
 2.48 2.6  2.72 2.84 2.96 3.   3.   3.   3.   3.   3.   3.   3.   3.
 3.   3.   3.   3.   3.   3.   3.   3.   3.12 3.24 3.36 3.48 3.6  3.72
 3.84 3.96 4.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4.
 4.   4.   4.   4.   4.   4.12 4.24 4.36 4.48 4.6  4.72 4.84 4.96 5.16
 5.4  5.64 5.88 6.12 6.36 6.6  6.84 7.04 7.16 7.28 7.4  7.52 7.64 7.76
 7.88]
